compile:
	javac -cp "/home/zeynep/.m2/repository/java-lsh-0.12.jar:/home/zeynep/.m2/repository/py4j-0.10.8.1.jar" HashApplication.java
run:
	java -cp .:/home/zeynep/.m2/repository/java-lsh-0.12.jar:/home/zeynep/.m2/repository/py4j-0.10.8.1.jar HashApplication
